version : '3'
services:
  dbservice-01:
    container_name: "dbservice-01"
    image: plan4ba/dbservice
    ports:
      - 8081:8080
    environment:
      - VIRTUAL_HOST=dbservice.localhost
      - VIRTUAL_PORT=8080
    extra_hosts:
          - "host-machine:172.17.0.1"
    volumes:
      - /home/mschaedlich/IdeaProjects/DBService/config.json:/app/config.json
networks:
  nginx-proxy:
    external: true